### ISSUE TITLE
Logging refinements

### ISSUE THREAD

**Issue by vreuter** [databio/pararead#22]
- [x] Remove `--logfile` and `--stream`, relying on default stream handler that we provide and use these options only if they're added by a developer
- [x] Remove `--loglevel`, favoring just `--verbosity`
- [x] Allow `--verbosity` argument to be a level name, while still interpreting integral values as they are now, as relative levels that we implicitly map into `logging` levels, so that we have the "higher level --> more messages" logic
- [x] Remove addition of `TRACE` with level of 5 from `setup_logger`

**Comment by nsheff** [comment]
Yes that is exactly how it makes the most sense to me (but I'm open to other opinions if you disagree).

The one thing I'm not sure of is the `TRACE` one. Is this what you are envisioning for the numeric mapping?

- `SILENT` -> 0 (?)
- `ERROR` -> 1
- `WARN` -> 2
- `INFO` -> 3 (default)
- `DEBUG` -> 4
- `TRACE` -> 5

**Comment by vreuter** [comment]
Yeah that's how I'd encode/map the levels as currently set. Should `TRACE` be removed altogether, though? Right now it's registered whenever a user calls `setup_logger`; I'm OK with leaving it that way but also think it'd be reasonable to have the base/default just be the standard `logging` levels.

**Comment by vreuter** [comment]
The hook remains but has been removed from the default configuration.
