### ISSUE TITLE
update docstrings

### ISSUE THREAD

**Issue by nsheff** [databio/pararead#34]
need to update docstrings for lucidoc.

**Comment by nsheff** [comment]
current render looks like: http://code.databio.org/pararead/autodoc_build/pararead/

**Comment by vreuter** [comment]
> current render looks like: http://code.databio.org/pararead/autodoc_build/pararead/

the commit deliberately didn't include a keyword that would close this

**Comment by nsheff** [comment]
That was intended to be the "before" part of the picture (my comment was before your commit)

**Comment by vreuter** [comment]
> That was intended to be the "before" part of the picture (my comment was before your commit)

You're right; sorry!

**Comment by nsheff** [comment]
I wasn't trying to passive-aggressive challenge your efficiency :attack:
