### ISSUE TITLE
quiet mode

### ISSUE THREAD

**Issue by nsheff** [databio/pararead#9]
pararead is quite verbose, when there are hundreds of chromosomes. it would be nice to have `--quiet`

or maybe just stick all the current output into a parallel log file (probably better) instead of to stdout.

**Comment by vreuter** [comment]
Agreed!

**Comment by vreuter** [comment]
Was looking at the interaction between the logging options that we provide through the standard `pararead` interface...specifying a value for `--logfile` should go ahead and mute the output to any standard stream, but I still agree that there should be a more binary/flag-like way to do this, or even have it be the default.

I think that there are two dimensions along which to consider the solution. The first is the destination for the messages (file vs. standard stream), and the second is which chromosomes/read chunks should generate a message.

**Comment by vreuter** [comment]
Here's my proposal for the default and for the alternate possibilities:
1. The default should still be to standard stream and not generate a logfile, but it should contain only messages about standard chromosome names (i.e., no underscores, `Un`, whatever)
2. `--quiet` or something similar should send that info to a logfile with some standard name, or should use the filepath given to `--logfile` if present.
3. `--silent` or something similar should result in NO logs, to standard stream or to logfile.
4. `-V` / `--verbose` should still only do normally-named chromosomes to standard stream, but should do everything to standard-named logfile or `--logfile` value.

**Comment by nsheff** [comment]
Good but I would skip `--silent`, and instead make `--quiet` do what you suggest for `--silent` if no `--logfile` is specified.

I would also *not* restrict to standard chromosome names, since the concept of 'standard' is species-specific.

**Comment by nsheff** [comment]
maybe now that we're taking a second look at pararead it's time to dive back into this? I'm not sure how far you got here...

but it did cause me think that we could probably write a logging package.

**Comment by vreuter** [comment]
> but it did cause me think that we could probably write a logging package.

that's fine, but it seems unlikely to be externally adopted

**Comment by vreuter** [comment]
Whatever you'd like done is fine; I have zero preference.

**Comment by vreuter** [comment]
> maybe now that we're taking a second look at pararead it's time to dive back into this? I'm not sure how far you got here...
> 
> but it did cause me think that we could probably write a logging package.

https://github.com/databio/logmuse

**Comment by nsheff** [comment]
I thought you were opposed to that :)
